name: QA release

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get current version
        id: get_semver
        uses: rickstaa/action-get-semver@v1

      - name: Pull Octopilot image
        run: docker pull ghcr.io/dailymotion-oss/octopilot:v1.9.7

      - name: Create PR with Octpilot in Deployment repo
        run: |
          docker run ghcr.io/dailymotion-oss/octopilot:v1.9.7 \
          --github-token ${{ secrets.DEPLOY_TESTER_REPO_ACCESS_TOKEN }} \
          --repo "thaboRach/deploy-tester" \
          --update "yaml(file=deployment.yml,path='frontend.qa')=${{ steps.get_semver.outputs.current_version }}" \
          --pr-title "Release: Promoting ${{ steps.get_semver.outputs.current_version }} to QA environment" \
          --pr-base-branch "main" \
          --pr-merge "true"
