# name: Release on Tag

# on:
#   push:
#     branches: main

# jobs:
#   release:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Bump version and push tag
#         id: tag_version
#         uses: mathieudutour/github-tag-action@v6.1
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18

#       - name: Install dependencies
#         run: yarn

#       - name: Upload artifact(build)
#         uses: actions/upload-artifact@v3
#         with:
#           name: build
#           path: build

#       - uses: vimtor/action-zip@v1
#         with:
#           files: build/
#           dest: build.zip

#       - name: Create Release
#         uses: ncipollo/release-action@v1
#         with:
#           name: Release ${{ github.ref_name }}
#           tag: ${{ steps.tag_version.outputs.new_tag }}
#           generateReleaseNotes: true
#           artifacts: build

#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
