name: Rollback
on:
  workflow_dispatch:

jobs:
  rollback:
    runs-on: ubuntu-latest
    environment: rollback

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Get previous version
      #   id: get_previous_semver
      #   run: |
      #     git fetch --tags
      #     latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
      #     previous_major_version=$(echo $latest_tag | grep -Eo '^v[0-9]+' | cut -d'v' -f2).0.0
      #     echo "previous_version=${previous_major_version}" >> $GITHUB_OUTPUT

      # - name: Get Previous version tag
      #   id: get_previous_tag
      #   run: |
      #     previous_major_version=${{ steps.get_previous_semver.outputs.previous_version }}
      #     previous_major_tag=$(git describe --tags --abbrev=0 "v$previous_major_version")
      #     echo "tag=${previous_major_tag}" >> $GITHUB_OUTPUT

      # - name: Get previous version
      #   id: get_previous_semver
      #   uses: sammcoe/get-previous-release-action@v1

      - name: Get current version
        id: get_semver
        uses: rickstaa/action-get-semver@v1

      - name: Get current major
        id: get_current_major
        run: |
          major=$( echo ${{ steps.get_semver.outputs.current_version }} | grep -Eo '^v[0-9]+' | cut -d'v' -f2 )
          echo "tag=${major}" >> $GITHUB_OUTPUT

      - name: Get previous version
        id: get_previous_semver
        shell: bash
        run: |
          prev=$( echo "${{ steps.get_current_major.outputs.tag }} - 1" | bc)
          echo "previous_version=v${prev}.0.0" >> $GITHUB_OUTPUT

      - name: Print Current Version
        run: |
          echo "Current Version: ${{ steps.get_semver.outputs.current_version }}"

      - name: Pull Octopilot image
        run: docker pull ghcr.io/dailymotion-oss/octopilot:v1.9.7

      - name: Create PR with Octpilot in Deployment repo
        run: |
          docker run ghcr.io/dailymotion-oss/octopilot:v1.9.7 \
          --github-token ${{ secrets.DEPLOY_TESTER_REPO_ACCESS_TOKEN }} \
          --repo "thaboRach/deploy-tester" \
          --update "yaml(file=deployment.yml,path='frontend.prod')=${{ steps.get_previous_semver.outputs.previous_version }}" \
          --pr-title "Release: Rollback Production from ${{steps.get_semver.outputs.current_version}} to  ${{ steps.get_previous_semver.outputs.previous_version }}" \
          --pr-base-branch "main" \
          --pr-merge "true"
