name: Rollback
on:
  workflow_dispatch:

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get previous version
        id: get_previous_semver
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "::set-output name=previous_version::${latest_tag}"

      - name: Use Previous Version
        run: |
          echo "Previous Version: ${{ steps.get_previous_semver.outputs.previous_version }}
