name: Update version and Create release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version name"
        required: true
        default: "minor"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: yarn

      - name: Upload artifact(build)
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

      - uses: vimtor/action-zip@v1
        with:
          files: build/
          dest: build.zip

      - name: Determine current version
        uses: rickstaa/action-get-semver@v1
        id: get_semver
        with:
          bump_level: "${{github.event.inputs.version}}"

      # - name: Determine current version
      #   id: version
      #   run: |
      #     current_version=$(git describe --tags --abbrev=0)
      #     echo "::set-output name=current_version::$current_version"

      # - name: Determine new version
      #   id: bump
      #   run: |
      #     new_version=$(semver bump ${{ github.event.inputs.version }} ${{ steps.version.outputs.tag }})
      #     echo "::set-output name=new_version::$new_version"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.ref_name }}
          tag: ${{ steps.get_semver.outputs.next_version }}
          generateReleaseNotes: true
          artifacts: build

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
