name: Update version and Create release

on:
  workflow_dispatch:
    inputs:
      version-bump:
        description: "Version name"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Upload artifact(build)
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

      - name: Archive artifact
        uses: vimtor/action-zip@v1
        with:
          files: build/
          dest: build.zip

      - name: Determine current version
        uses: rickstaa/action-get-semver@v1
        id: get_semver
        with:
          bump_level: "${{github.event.inputs.version-bump}}"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ steps.get_semver.outputs.next_version }}
          tag: ${{ steps.get_semver.outputs.next_version }}
          generateReleaseNotes: true
          artifacts: build

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Octopilot image
        run: docker pull ghcr.io/dailymotion-oss/octopilot:v1.9.7

      - name: Create PR with Octpilot in Deployment repo
        run: |
          docker run ghcr.io/dailymotion-oss/octopilot:v1.9.7 \
          --github-token ${{ secrets.DEPLOY_TESTER_REPO_ACCESS_TOKEN }} \
          --repo "deploy-tester" \
          --update "yaml(file=deployment.yaml,path='frontend.dev')=${{ steps.get_semver.outputs.next_version }}" \
          --update "yaml(file=deployment.yaml,path='frontend.qa')=${{ steps.get_semver.outputs.next_version }}" \
          --pr-title "Release: Promoting ${{ steps.get_semver.outputs.next_version }} to Dev & QA environment" \
          --pr-base-branch "main" \
          --pr-merge "true"
